dag_id: "dag_z_multi_task"
description: "DAG simples com uma tarefa bash gerada dinamicamente"
schedule_interval: None
imports: |
  from airflow.operators.bash import BashOperator
  from airflow.operators.python import PythonOperator
  from modules.test_python_call import print_message
tags:
  - "dynamic"
  - "bash"
  - "simple"
  - "python"

tasks:
  - task_id: "hello_world"
    type: "bash"
    bash_command: "echo 'Hello World from Dynamic DAG!'"

  - task_id: "call_python"
    type: "python"
    python_callable: "print_message"
    op_kwargs:
      msg: "Hello from Dynamic DAG!"

  - task_id: "print_message_task"
    type: "python"
    python_callable: "print_message"
    op_kwargs:
      msg: "Hello from another Python task!"

dependencies:
  - upstream: "hello_world"
    downstream: "call_python"    
  - upstream: "call_python"
    downstream: "print_message_task"
  
