version: '3'
services:
  dbt:
    container_name: dbt
    build: .
    image: dbt-dummy
    volumes:
      - .:/dbt
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    volumes:
      - ./files:/files
      - ./copy_postgres.sh:/copy_postgres.sh
    ports:
      - "5432:5432"
    