cosmos:
  outputs:
    dev:
      type: postgres #Tipo do conector
      threads: 2
      host: postgres #Host do postgres
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: pokedex
      schema: dbt_asafe #Schema onde o resultados dos modelos serão salvos
      
    bq:
      type: bigquery
      method: service-account
      project: "{{env_var('GCP_PROJECT_ID') }}"
      dataset: "{{env_var('DBT_DATASET_NAME') }}"
      threads: 4 # Must be a value of 1 or greater
      keyfile: /opt/airflow/dbt-key.json #Schema onde o resultados dos modelos serão salvos

  target: dev